# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_MEMORY = "2048"
VMNAME = "zfsvm"

PGPORT = "5432"
PGUSER = "dbadmin"
PGPASSWORD = "devved"
PGDATABASE = "testdb"
PGVERSION = "13"


Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |vb, orvb|
		orvb.vm.synced_folder '../', '/home/vagrant/zfs_initial_setup', create:true, :mount_options => ['dmode=775', 'fmode=777']
		orvb.vm.network "private_network", ip: "192.168.56.78"
		vb.customize ["modifyvm", :id, "--memory", SERVER_MEMORY]
		vb.name = VMNAME
	end

	config.vm.disk :disk, name: "dev1", size: "25GB"
	config.vm.disk :disk, name: "dev2", size: "25GB"
	config.vm.disk :disk, name: "dev3", size: "25GB"

	config.vm.define "zfsvm" do |zfsvm|
		zfsvm.vm.box = "generic/ubuntu2004"
		zfsvm.vm.hostname = "zfsvm"
		zfsvm.vm.provision :shell do |s|
			s.path = "provision.sh"
			s.env = {
				"PGPORT" => PGPORT,
				"PGUSER" => PGUSER,
				"PGPASSWORD" => PGPASSWORD,
				"PGDATABASE" => PGDATABASE,
				"PGVERSION" => PGVERSION,
			}
		end
	end

end
